# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 134f429683d297fc4f716e9e2d52ebb24bf1ce335098902dfaba5fa7e9d0c1a9c5783ceee1bf01001e8065151bc802a09ecc3dc960b455b27c780c656cfd0f3f

test:
  secret_key_base: 86b4afe85c497fdf4b1b663fd8135b0ac32d6793269df5c0827ebafade7f83b6db5b1a2e870edbdea4163601297babb6032c206b3d99dc95dd965ae54a6557b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
